### PR TITLE
Add support for Python 3.11

### PR DESCRIPTION
**Pull request by timobrembeck**
Thanks for this tool, especially since [Giphy/giphy-python-client](https://github.com/Giphy/giphy-python-client) seems to be pretty dead.

I don't see a particular reason why this package shouldn't be working with Python 3.11.
I'm sorry if I missed something and this version constraint was on purpose.
Thanks a lot in advance for your feedback!

### CODE REVIEW

**Comment by zschumacher** [comment]
Thanks for the PR! As you said no reason other than I haven’t got around to it. 

This looks good to me, can you just remove the release notes? CI takes care of that for you.

**Comment by timobrembeck** [comment]
Thanks for the quick reply! Should I also look into the failing build, or is that something unrelated to my changes?

> This looks good to me, can you just remove the release notes? CI takes care of that for you.

Sure, did that!

**Comment by zschumacher** [comment]
> Thanks for the quick reply! Should I also look into the failing build, or is that something unrelated to my changes?
> 
> > This looks good to me, can you just remove the release notes? CI takes care of that for you.
> 
> Sure, did that!

You fixed it, for some reason 3.9.9 has issues with GHA

**Review by zschumacher — APPROVED** [review]

**Comment by zschumacher** [comment]
@timoludwig just released this in `0.1.2`

**Pull request merged**
